language: java
os: linux
dist: focal
jdk: openjdk25

services:
  - xvfb

before_install:
  - export PATH=$GRADLE_HOME/bin:$PATH

cache:
  directories:
    - '$HOME/.sonar/cache'

script:
  - ./gradlew --info check

#script:
#  - pwd
#  - env
#  - find .
#  - ./gradlew --info check
